name: Update index.html with current time

on:
    push:
        branches: [ main ]
        # main에서 동작하도록함.

permissions:
    contents: write
    #컨텐츠에 대해서 write 권한을 주겠다는 의미.


#작업 설정
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4 #체크아웃을 먼저 해야 진행이됨.

        - name: Set up Python 3.11
          uses: actions/setup-python@v3
          with:
            python-version: 3.11
        
        - name: Install dependencies #필요한 디펜던시 설치
          run: |
            python -m pip install --upgrade pip
            python -m pip install flake8 pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: Lint with flake8
          #건너뜀

        - name: Run Python script #파이썬 코드 실행
          run: |
            python update_time.py

        - name: Commit updated index.html
          uses: EndBug/add-and-commit@v7
          with:
            author_name: SongMinjun
            author_emial: minjunevmf2@gmail.com
            message: Update index.html with current time
            add: 'index.html'